// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkvxtukxlinrndvanpwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdnh0dWt4bGlucm5kdmFucHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTgxMjIsImV4cCI6MjA3MzM5NDEyMn0.L7Jt8p-TWx7iT5BtqG5sCnuTvvAQaPjVG01DaWsGpGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});